name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]
        
    runs-on: windows-latest
    
    env:
      Project_Name: XcloudInputEmulator
      Project_Path: XcloudInputEmulator\XcloudInputEmulator.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
     
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Build the application
      run: dotnet build $env:Project_Path -c $env:Configuration
      
      env:
        Configuration: ${{ matrix.configuration }}
        
    - name: List files on build path
      run: dir ${{ github.workspace }}\${{ env.Project_Name }}\bin\${{ matrix.configuration }}\net7.0-windows
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name:  ${{ matrix.configuration }} Build
        path: ${{ github.workspace }}\${{ env.Project_Name }}\bin\${{ matrix.configuration }}\net7.0-windows\**\*
        if-no-files-found: error